'use client'

import { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'ja' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  ja: {
    'title': 'YouTube動画構造分析ツール',
    'description': 'YouTube動画の構造をAIで分析します',
    'hero.title.line1': 'なぜあの動画は伸びて、',
    'hero.title.line2': 'あなたの動画は伸びないのか。',
    'hero.subheadline': 'センスより、構造。',
    'hero.badge': 'AI動画構造分析',
    'hero.cta': 'すぐに分析してみる',
    'hero.ctaNote': '初回1回無料',
    'hero.stat1.label': '動画分析数',
    'hero.stat2.label': 'プロンプト生成',
    'hero.stat2.suffix': 'パターン',
    'hero.stat3.label': '対応モード',
    'hero.stat3.suffix': '種類',
    'mode.buzz.title': 'バズ分析',
    'mode.buzz.desc': 'バズった動画のURLを入力 → なぜ伸びたか構造的に分析',
    'mode.buzz.tag1': '構造分析',
    'mode.buzz.tag2': 'フック解説',
    'mode.buzz.tag3': '感情設計',
    'mode.buzz.tag4': '参考事例化',
    'mode.growth.title': 'Growth',
    'mode.growth.desc': 'あなたの動画を伸ばす設計を',
    'mode.growth.tag1': '改善提案',
    'mode.growth.tag2': '競合比較',
    'mode.growth.tag3': '次回作アイデア',
    'mode.growth.tag4': '台本プロンプト',
    'input.buzz.title': 'バズ分析',
    'input.growth.title': 'バズりたい',
    'input.growth.feature1': '改善提案レポート',
    'input.growth.feature2': '次回作アイデア4つ',
    'input.growth.feature3': '台本・動画プロンプト生成',
    'input.growth.subtitle': 'あなたの動画を分析して改善点を提案します',
    'input.growth.comparisonBadge': '差分比較レポートが生成されます',
    'input.buzz.subtitle': 'バズった動画の構造を分析します',
    'input.back': 'モード選択に戻る',
    'signup.error.required': 'メールアドレスを入力してください',
    'signup.error.invalid': '有効なメールアドレスを入力してください',
    'hero.sub.line1': 'YouTubeのURLを入力するだけで',
    'hero.sub.line2': 'バズ動画の構造と改善ポイントを自動分析',
    'hero.sub.line3': '分析結果から、次に作るべき動画の台本・映像プロンプトも自動生成。',
    'header.title': 'バズ構造分析',
    'header.pricing': '料金プラン',
    'header.trial': '無料で試す',
    'input.heading': 'AI 構造分析',
    'input.label': 'YouTube動画のURLを入力してください',
    'input.placeholder': 'https://youtube.com/watch?v=... または https://youtube.com/shorts/...',
    'input.videoType': '動画タイプ',
    'input.videoType.short': 'ショート動画',
    'input.videoType.regular': '通常動画',
    'input.error.required': 'URLを入力してください',
    'input.error.invalidYoutube': '有効な YouTube のURLを入力してください',
    'input.footerNote': 'アカウント不要。まず動画情報が表示され、続けてAI分析が行われます。',
    'input.button': 'AIで分析する',
    'input.samples': 'サンプル動画を試す:',
    'input.sample1': 'サンプル 1',
    'input.sample2': 'サンプル 2',
    'input.sample3': 'サンプル 3',
    'processing.title': '動画を分析中...ちょっと待ってね',
    'processing.fetchingMetadata': '動画情報を取得しています…',
    'processing.step1': 'AIモデルを初期化中',
    'processing.step2': '動画メタデータを取得中',
    'processing.step3': 'コンテンツを分析中',
    'processing.step4': 'レポートを生成中',
    'processing.progress': '進捗',
    'processing.error.analyzeFailed': '分析に失敗しました',
    'processing.error.analyzeEmpty': '分析結果を取得できませんでした',
    'processing.error.limitExceeded': '分析回数の上限に達しました。プランをアップグレードしてください。',
    'processing.error.openaiRateLimit':
      'OpenAI の一時的な上限（レート制限）に達しました。2〜5分ほど空けてから再度お試しください。繰り返す場合は platform.openai.com の請求・利用枠を確認するか、OPENAI_MODEL を gpt-4o-mini にすると改善することがあります。',
    'processing.error.needAuth': 'セッションがありません。ページを再読み込みしてください。',
    'processing.error.unauthorized': '認証に失敗しました。再度ログインしてください。',
    'processing.error.supabase': 'Supabase が未設定です。.env.local を確認してください。',
    'signup.error.supabase': 'Supabase が未設定です',
    'signup.error.passwordLength': 'パスワードは6文字以上にしてください',
    'signup.passwordPlaceholder': 'パスワード（6文字以上）',
    'results.title': '分析結果',
    'results.videoInfo': '動画情報',
    'results.views': '再生回数',
    'results.titleUnknown': 'タイトル未取得',
    'results.channelUnknown': 'チャンネル名未取得',
    'results.statUnavailable': '未取得',
    'results.likes': 'いいね',
    'results.duration': '再生時間',
    'results.trendScore': 'トレンドスコア',
    'results.aiAnalysis': 'AI構造分析',
    'results.loading.title': '分析中・・・・',
    'results.loading.sub': 'AIが動画構造を解析しています。',
    'results.analyzing': '分析中…',
    'results.hook': 'フック',
    'results.emotion': 'エモーション',
    'results.structure': 'ストラクチャー',
    'results.cta': 'CTA',
    'results.retention': 'リテンション',
    'results.hook.value': '質問型フック',
    'results.hook.desc': '冒頭で挑発的な質問を投げかけ、視聴者の注意を瞬時に引きつけます。',
    'results.emotion.value': '好奇心 + 不安',
    'results.emotion.desc': '2つの感情を同時に刺激し、最後まで視聴させる効果があります。',
    'results.structure.value': '課題 → 解決型',
    'results.structure.desc': '問題提起から解決策の提示まで、3幕構成で展開しています。',
    'results.cta.value': 'フォロー誘導型',
    'results.cta.desc': '押し付けがましくないソフトなCTAでフォロワー増加を促進します。',
    'results.retention.value': '72% — 高評価',
    'results.retention.desc': '構成パターンから予測される視聴維持率は平均以上です。',
    'results.improvements': '改善提案',
    'results.competitorSection': '競合比較分析',
    'results.competitorSectionTitle': 'メイン動画と競合の比較',
    'results.competitorStrengths': '競合動画が優れている点（3つ）',
    'results.yourWeaknesses': '自分の動画に足りない要素（3つ）',
    'results.priorityImprovements': '今すぐ改善すべき優先度TOP3',
    'results.competitorMissing': '競合比較データを取得できませんでした。しばらくしてから再度分析してください。',
    'results.improvementsTitle': '改善アイデア',
    'results.improvement1': '最初の3秒でフックを改善 — 結果を先に見せることを検討。',
    'results.improvement2': 'より個人的なストーリーで感情的なトリガーを強化。',
    'results.improvement3': '20秒時点でより明確なCTAを追加。最後だけでなく。',
    'results.improvement4': 'ミュート視聴者のために画面上のテキストで重要ポイントを強調。',
    'results.improvement5': '中間部分を4〜5秒トリミングしてテンポを引き締める。',
    'results.ideas': '次の動画アイデア',
    'results.ideasTitle': '次に試すべき動画コンセプト',
    'results.idea1': '「初心者がやりがちな3つの間違い」',
    'results.idea2': '「これを30日間試したらどうなる？」',
    'results.idea3': '「予想外の結果実験 — #3は信じられない」',
    'results.idea4': '「誰も教えてくれない60秒バージョン」',
    'results.nextVideo': '次の動画を分析',
    'results.newAnalysis': '新しい分析',
    'results.sourceThumbTitle': 'サムネ評価・改善案',
    'results.sourceThumbHint':
      '入力したURLのサムネ画像をAIが見てスコアと改善案を出しています（サムネが取得できたときだけ表示されます）。',
    'results.sourceThumbScore': '総合スコア',
    'results.sourceThumbComment': '評価コメント',
    'results.sourceThumbIdeas': 'サムネ向けの改善案（ここを見る）',
    'results.improvementsThumbNote':
      '※ サムネ画像専用の改善案は、上の「サムネ評価・改善案」にあります（表示される場合のみ）。',
    'results.taggedImprovementsTitle': '追加の改善ヒント（タグ付き）',
    'results.taggedImprovementsHint': 'サムネ分析と同じ結果から、フック・テンポなどの観点も含めた提案です。',
    'header.language': '言語',
    'hero.stats.analyses': '12,400+',
    'hero.stats.analysesLabel': '動画分析',
    'hero.stats.patterns': '4',
    'hero.stats.patternsLabel': 'プロンプト',
    'hero.stats.modes': '2',
    'hero.stats.modesLabel': 'モード',
    'hero.videoCardLabel': '実例：バズった動画',
    'mode.buzz': 'バズ分析',
    'mode.buzzSub': 'バズった動画を分析',
    'mode.buzzDesc': '既に流行った動画から、バズる法則を学ぶ',
    'mode.growth': 'バズりたい',
    'mode.growthSub': 'ライバル比較で成長',
    'mode.growthDesc': '自分の動画とライバル比較で、改善策を発見',
    'mode.select': 'このモードを選ぶ',
    'input.modeTitle': '分析モード',
    'input.singleUrl': '分析する動画URL',
    'input.compareUrl': '比較するライバル動画URL',
    'input.competitorBadge': 'ライバル比較',
    'signup.title': 'アカウントを作成',
    'signup.subtitle': 'より詳しい分析結果を受け取りましょう',
    'signup.email': 'メールアドレス',
    'signup.emailPlaceholder': 'your@email.com',
    'signup.password': 'パスワード',
    'signup.signupButton': 'アカウント作成',
    'signup.googleButton': 'Googleで登録',
    'signup.terms': '登録することで、利用規約に同意します。',
    'upgrade.title': 'アップグレード',
    'upgrade.subtitle': 'さらに詳しい分析を解放',
    'upgrade.free': 'フリー',
    'upgrade.freePrice': '無料',
    'upgrade.freeFeature1': '基本的な動画分析',
    'upgrade.freeFeature2': '改善アイデア',
    'upgrade.freeFeature3': '月1回の分析',
    'upgrade.pro': 'プロ',
    'upgrade.proPrice': '¥1,980',
    'upgrade.proFeature1': 'すべてのフリー機能',
    'upgrade.proFeature2': 'プロンプト自動生成',
    'upgrade.proFeature3': '月30回の分析',
    'upgrade.proFeature4': 'ライバル比較機能',
    'upgrade.business': 'ビジネス',
    'upgrade.businessPrice': '¥4,980',
    'upgrade.businessFeature1': 'すべてのプロ機能',
    'upgrade.businessFeature2': '無制限分析',
    'upgrade.businessFeature3': 'チーム管理',
    'upgrade.businessFeature4': 'データエクスポート',
    'upgrade.currentPlan': '現在のプラン',
    'upgrade.selectPlan': 'プランを選択',
    'locked.requiresPro': 'プロプランで解放',
    'locked.requiresBusiness': 'ビジネスプランで解放',
    'locked.unlock': 'アップグレードして解放',
  },
  en: {
    'title': 'YouTube Video Structure Analyzer',
    'description': 'Analyze the structure of YouTube videos using AI.',
    'hero.title.line1': 'Why does that video go viral',
    'hero.title.line2': 'while yours doesn\'t?',
    'hero.subheadline': 'Structure over talent.',
    'hero.badge': 'AI Video Analyzer',
    'hero.cta': 'Start Analyzing',
    'hero.ctaNote': '1 free analysis included',
    'hero.stat1.label': 'Videos Analyzed',
    'hero.stat2.label': 'Prompt Patterns',
    'hero.stat2.suffix': 'types',
    'hero.stat3.label': 'Analysis Modes',
    'hero.stat3.suffix': 'available',
    'mode.buzz.title': 'Research Mode',
    'mode.buzz.desc': 'Analyze viral videos to understand why they succeeded',
    'mode.buzz.tag1': 'Structure analysis',
    'mode.buzz.tag2': 'Hook breakdown',
    'mode.buzz.tag3': 'Emotion design',
    'mode.buzz.tag4': 'Reference example',
    'mode.growth.title': 'Growth',
    'mode.growth.desc': 'Design your video for growth',
    'mode.growth.tag1': 'Improvement ideas',
    'mode.growth.tag2': 'Competitor comparison',
    'mode.growth.tag3': 'Next video ideas',
    'mode.growth.tag4': 'Script prompt',
    'input.buzz.title': 'Research Mode',
    'input.growth.title': 'Growth Mode',
    'input.growth.feature1': 'Improvement report',
    'input.growth.feature2': '4 video ideas',
    'input.growth.feature3': 'Script & video prompts',
    'input.growth.subtitle': 'Analyze your video and get improvement suggestions',
    'input.growth.comparisonBadge': 'A comparison report will be generated',
    'input.buzz.subtitle': 'Analyze why viral videos succeeded',
    'input.back': 'Back to mode selection',
    'signup.error.required': 'Please enter an email address',
    'signup.error.invalid': 'Please enter a valid email address',
    'hero.sub.line1': 'See the flow (hook, build, payoff),',
    'hero.sub.line2': 'get fixes and your next hit ideas — automatically.',
    'hero.sub.line3': 'Also generates scripts & video prompts for your next videos.',
    'header.title': 'YT Structure AI',
    'header.pricing': 'Pricing',
    'header.trial': 'Free Trial',
    'input.heading': 'AI structure',
    'input.label': 'Enter a YouTube video URL',
    'input.placeholder': 'https://youtube.com/watch?v=... or https://youtube.com/shorts/...',
    'input.videoType': 'Video Type',
    'input.videoType.short': 'Shorts',
    'input.videoType.regular': 'Regular Video',
    'input.error.required': 'Please enter a URL',
    'input.error.invalidYoutube': 'Please enter a valid YouTube URL',
    'input.footerNote': 'No account required. Video details appear first, then AI analysis runs.',
    'input.button': 'Analyze with AI',
    'input.samples': 'Try sample videos:',
    'input.sample1': 'Sample 1',
    'input.sample2': 'Sample 2',
    'input.sample3': 'Sample 3',
    'processing.title': 'Analyzing Video...',
    'processing.fetchingMetadata': 'Fetching video information…',
    'processing.step1': 'Initializing AI model',
    'processing.step2': 'Fetching video metadata',
    'processing.step3': 'Analyzing content',
    'processing.step4': 'Generating report',
    'processing.progress': 'Progress',
    'processing.error.analyzeFailed': 'Analysis failed',
    'processing.error.analyzeEmpty': 'Could not retrieve analysis results',
    'processing.error.limitExceeded': 'You have reached your analysis limit. Please upgrade your plan.',
    'processing.error.openaiRateLimit':
      'OpenAI rate limit (429). Wait 2–5 minutes and try again. If it keeps happening, check billing and limits at platform.openai.com/account/billing or use OPENAI_MODEL=gpt-4o-mini.',
    'processing.error.needAuth': 'No session. Please reload the page.',
    'processing.error.unauthorized': 'Authentication failed. Please sign in again.',
    'processing.error.supabase': 'Supabase is not configured. Check .env.local.',
    'signup.error.supabase': 'Supabase is not configured',
    'signup.error.passwordLength': 'Password must be at least 6 characters',
    'signup.passwordPlaceholder': 'Password (6+ characters)',
    'results.title': 'Analysis Results',
    'results.videoInfo': 'Video Information',
    'results.views': 'Views',
    'results.titleUnknown': 'Title unavailable',
    'results.channelUnknown': 'Channel unavailable',
    'results.statUnavailable': '—',
    'results.likes': 'Likes',
    'results.duration': 'Duration',
    'results.trendScore': 'Trend Score',
    'results.aiAnalysis': 'AI Structure Analysis',
    'results.loading.title': 'Analyzing…',
    'results.loading.sub': 'AI is mapping the video structure.',
    'results.analyzing': 'Analyzing…',
    'results.hook': 'Hook Type',
    'results.emotion': 'Emotion Type',
    'results.structure': 'Structure Type',
    'results.cta': 'CTA Type',
    'results.retention': 'Retention Prediction',
    'results.hook.value': 'Question Hook',
    'results.hook.desc': 'Opens with a provocative question to instantly grab attention.',
    'results.emotion.value': 'Curiosity + Fear',
    'results.emotion.desc': 'Triggers dual emotional response for maximum watch-through.',
    'results.structure.value': 'Problem → Solution',
    'results.structure.desc': 'Classic 3-act structure: pain point, buildup, resolution.',
    'results.cta.value': 'Follow for More',
    'results.cta.desc': 'Soft CTA driving follower growth without friction.',
    'results.retention.value': '72% — High',
    'results.retention.desc': 'Estimated above-average retention based on structure patterns.',
    'results.improvements': 'Improvement Suggestions',
    'results.competitorSection': 'Competitor comparison',
    'results.competitorSectionTitle': 'Your video vs. competitor',
    'results.competitorStrengths': "What the competitor does better (3)",
    'results.yourWeaknesses': "What your video is missing (3)",
    'results.priorityImprovements': 'Top 3 priority fixes',
    'results.competitorMissing': 'Competitor comparison data was not returned. Try analyzing again in a moment.',
    'results.improvementsTitle': 'Improvement Ideas',
    'results.improvement1': 'Improve hook in the first 3 seconds — consider showing the outcome first.',
    'results.improvement2': 'Increase emotional trigger with a more personal story angle.',
    'results.improvement3': 'Add a clearer CTA at the 20-second mark, not just the end.',
    'results.improvement4': 'Use on-screen text to reinforce key points for muted viewers.',
    'results.improvement5': 'Trim the middle section by 4–5 seconds to tighten pacing.',
    'results.ideas': 'Next Video Ideas',
    'results.ideasTitle': 'Video Concepts to Try Next',
    'results.idea1': '"3 mistakes beginners make with this"',
    'results.idea2': '"What happens if you try this for 30 days?"',
    'results.idea3': '"Unexpected result experiment — you won\'t believe #3"',
    'results.idea4': '"The 60-second version nobody told you about"',
    'results.nextVideo': 'Analyze Next Video',
    'results.newAnalysis': 'New Analysis',
    'results.sourceThumbTitle': 'Thumbnail review & fixes',
    'results.sourceThumbHint':
      'AI scores your thumbnail from the URL you entered and lists thumbnail-specific fixes (only when a thumbnail is available).',
    'results.sourceThumbScore': 'Overall score',
    'results.sourceThumbComment': 'Notes',
    'results.sourceThumbIdeas': 'Thumbnail improvement ideas (see below)',
    'results.improvementsThumbNote':
      'Tip: Thumbnail-specific ideas appear in “Thumbnail review & fixes” above when available.',
    'results.taggedImprovementsTitle': 'More suggestions (tagged)',
    'results.taggedImprovementsHint': 'From the same pass as the thumbnail review, including hook and pacing.',
    'header.language': 'Language',
    'hero.stats.analyses': '12,400+',
    'hero.stats.analysesLabel': 'Videos Analyzed',
    'hero.stats.patterns': '4',
    'hero.stats.patternsLabel': 'Prompt Patterns',
    'hero.stats.modes': '2',
    'hero.stats.modesLabel': 'Analysis Modes',
    'hero.videoCardLabel': 'Real Example: Viral Video',
    'mode.buzz': 'Research Mode',
    'mode.buzzSub': 'Analyze viral videos',
    'mode.buzzDesc': 'Learn viral patterns from trending videos',
    'mode.growth': 'Growth Mode',
    'mode.growthSub': 'Competitor comparison',
    'mode.growthDesc': 'Compare your video with competitors and find improvements',
    'mode.select': 'Select Mode',
    'input.modeTitle': 'Analysis Mode',
    'input.singleUrl': 'Video URL to analyze',
    'input.compareUrl': 'Competitor video URL',
    'input.competitorBadge': 'Competitor Comparison',
    'signup.title': 'Create Account',
    'signup.subtitle': 'Get deeper analysis results',
    'signup.email': 'Email Address',
    'signup.emailPlaceholder': 'your@email.com',
    'signup.password': 'Password',
    'signup.signupButton': 'Create Account',
    'signup.googleButton': 'Sign up with Google',
    'signup.terms': 'By signing up, you agree to our Terms of Service.',
    'upgrade.title': 'Upgrade',
    'upgrade.subtitle': 'Unlock advanced analysis',
    'upgrade.free': 'Free',
    'upgrade.freePrice': 'Free',
    'upgrade.freeFeature1': 'Basic video analysis',
    'upgrade.freeFeature2': 'Improvement ideas',
    'upgrade.freeFeature3': '1 analysis per month',
    'upgrade.pro': 'Pro',
    'upgrade.proPrice': '$19.99',
    'upgrade.proFeature1': 'All free features',
    'upgrade.proFeature2': 'Auto-generate prompts',
    'upgrade.proFeature3': '30 analyses per month',
    'upgrade.proFeature4': 'Competitor comparison',
    'upgrade.business': 'Business',
    'upgrade.businessPrice': '$49.99',
    'upgrade.businessFeature1': 'All pro features',
    'upgrade.businessFeature2': 'Unlimited analyses',
    'upgrade.businessFeature3': 'Team management',
    'upgrade.businessFeature4': 'Data export',
    'upgrade.currentPlan': 'Current Plan',
    'upgrade.selectPlan': 'Select Plan',
    'locked.requiresPro': 'Unlock with Pro',
    'locked.requiresBusiness': 'Unlock with Business',
    'locked.unlock': 'Upgrade to unlock',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ja')

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
